### ISSUE TITLE
function colorize16 isn't defined

### ISSUE THREAD

**Issue by stephenwithav** [Zenithar/hughostium#1]
What should the function colorize16 do?  I'll gladly implement it and submit a PR.

**Comment by Zenithar** [comment]
It's only available on my fork ^^ It generates a color according a string. Maybe not really useful for you ^^ 

https://github.com/Zenithar/hugo/blob/master/helpers/colorize.go

**Comment by stephenwithav** [comment]
Thanks for pointing me to the code.

Would you mind if I implement the function as a shortcode and submit it as a PR?

**Comment by Zenithar** [comment]
The PR has been done but rejected ^^

https://github.com/spf13/hugo/pull/289
